server:
  port: 8010
spring:
  application:
    name: postService
  datasource:
    url: jdbc:mysql://localhost:3306/forum_post?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
  mail:
    host: smtp.163.com
    username: m2541994309@163.com
    password: VTAOZRVFUNMCUEAI
    port: 994
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: Gz
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  #mybatis-plus配置控制台打印完整带参数SQL语句
#  level:
#    com.wbm.forum.mapper: debug
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka
