server:
  port: 6001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user-service
          uri: lb://userService
          predicates:
            - Path=/user/**
        - id: popst-service
          uri: lb://postService
          predicates:
            - Path=/post/**